### ISSUE TITLE
User Management/Visitor: Create favorites 

### ISSUE THREAD

**Issue by amrouda50** [amrouda50/destination-finder#5]
As part of enhancing user experience the proposal is to create certain user specific data (seasonal data #7 also included) 

- [x] Create history of already visited regions
- [x] Create Watchlists [! List of personalized recommendations]
- [x] Create favorite regions
- [x] Sequences of regions (like groups created manually by user)

**Comment by havenousername** [comment]
@amrouda50  Favourite regions feature is presented on server side

**Comment by havenousername** [comment]
For the watchlists I suggest to use similar to youtube implementation
<img width="928" alt="image" src="https://github.com/amrouda50/destination-finder/assets/40630843/690df42a-06a9-4b1d-acd3-965ac4113b10">

**Comment by havenousername** [comment]
Watchlists, Favourite regions and history entities have been created
