### ISSUE TITLE
Peek seasons: Frontend Integration

### ISSUE THREAD

**Issue by amrouda50** [amrouda50/destination-finder#7]
After creating peek seasons and improving algorithm, having a authorized user can give some more flexibility and insight on the frontend side. These are some proposals that could be implemented as part of the pipeline:

- [x] The history of visited regions with season (region preference)
- [x] The history of the liked seasons per region (seasons preference)
- [x] The view for both of those live in the map (recolor the map accordingly)

**Comment by havenousername** [comment]
```ts
type VisitedRegion {
   months: Month[];
   name: string;
}


type UserStats {
  visitedRegions: VisitedRegion[];
  favouriteRegions: 
}
```

**Comment by havenousername** [comment]
What do we have 
- For the season 
  1. Backend/Json to strapi 
  2. Frontend adjustment
  3. Change data from synthetic to real 
  4. Add pricing to the clustering algorithm
- Personal recommendation
