### ISSUE TITLE
User Management/Visitor: Profile information

### ISSUE THREAD

**Issue by amrouda50** [amrouda50/destination-finder#8]
Profile information can give extra information about the user preferences. Gather this idea to adjust watchlist suggestions and further personal suggestion enhancement
Frontend
- [x] Photos from the visited countries
- [x] Some short reviews, etc...

**Comment by havenousername** [comment]
@amrouda50 New database entity called `visits` is added.  Visits are created by the users(many-to-many) and are held by the regions (one-to-many from regions pov). These `visits` are part of user statistics and will be a private part of the application

**Comment by havenousername** [comment]
Check those: 

- [ ] Groups API
- [ ]

**Comment by havenousername** [comment]
https://www.postman.com/planetary-robot-997810/workspace/destirec/collection/14947473-563f1652-039b-4ed7-8399-494fb3895081?action=share&creator=14947473

Pull the changes from `master` https://github.com/amrouda50/destination-finder-server
